UPDATE rooms
SET type_room = CASE
    WHEN number = 101 THEN 'ELECTROTECHNICS_LABORATORY'
    WHEN number IN (102, 103) THEN 'ELECTRONICS_LABORATORY'
    WHEN number IN (109, 202, 204, 205, 206, 207, 211, 212, 213, 214) THEN 'COMPUTER_LABORATORY'
    WHEN number = 110 THEN 'CNC_SIMULATION'
    WHEN number IN (201, 203) THEN 'CLASSROOM'
    WHEN type_room = 'CLASSROOM' THEN 'CLASSROOM'
    WHEN type_room = 'AUDITORIUM' THEN 'CNC_SIMULATION'
    ELSE 'COMPUTER_LABORATORY'
END;
